site_name: Tickethost
site_url: http://localhost:8000 #http://docs.tickethost.co.zm
nav:
  - index.md
  - getting_started/index.md
  - Tickets:
    - tickets/index.md
  - Event Organiser(s):
    - organisers/index.md
    - organisers/create_event.md
    - organisers/manage_event.md

theme:
  icon:
    logo: material/ticket-confirmation-outline
  favicon: images/tickethost_zm_cover.png
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tickethostinfo
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tickethostzambia
  homepage: https://tickethost.co.zm
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >- 


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format